name: week7_lab2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/fox.jpg

  fonts:
     - family: Roboto
       fonts:
         - asset: fonts/roboto_black.ttf
         - weight: 700
         - asset: fonts/roboto_bold.ttf
         - weight: 600
         - asset: fonts/roboto_medium.ttf
         - weight: 500
         - asset: fonts/roboto_regular.ttf
         - weight: 400
         - asset: fonts/roboto_light.ttf
         - weight: 300


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
